### ISSUE TITLE
Support for ForeFlight checklists

### ISSUE THREAD

**Issue by zyv** [rdamazio/efis-editor#40]
Hi,

Your checklist editor looks fantastic! I wish it supported the ForeFlight format (FMD) as well, so that I could edit checklists on a PC.

I've had a look at the files myself, and apparently are not compressed, but encrypted, so it doesn't seem like it's going to be an easy ride. I've also opened an official support ticket (1704642) requesting any kind of information about the file format, but somehow I'm not holding my breath.

Do you have concerns reversing the format if ForeFlight refuses to cooperate?

P.S. Why in the world one would even go through the trouble spending resources on encrypting CHECKLIST FILES?!!111 of all things? Is there any kind of tenable rational explanation for this bizarre decision?

**Comment by rdamazio** [comment]
Thanks for the FR!

You're not the first to ask for this ([VAF thread](https://vansairforce.net/threads/web-based-checklist-editor.226809/)), and back then I did some digging - it seems to be encrypted JSON, and there are also numerous reddit threads about it, but sadly nobody has come up with a way to read or write it. If you manage to reverse it, or convince Foreflight to release details, I think a lot of people would be very happy :) PRs welcome.

> P.S. Why in the world one would even go through the trouble spending resources on encrypting CHECKLIST FILES?!!111 of all things? Is there any kind of tenable rational explanation for this bizarre decision?

Wild guess: if they let anyone write their checklist format, they have to make the app resilient to all sorts of badly-formatted files, as well as provide support for using checklists imported this way...

**Comment by zyv** [comment]
> If you manage to reverse it, or convince Foreflight to release details, I think a lot of people would be very happy :)

Challenge accepted! (tm)

I talked to ForeFlight support, but I can't say it was very productive.

First, when I asked for the encryption and format details, they claimed that it didn't even make sense to edit checklists on a computer because there was no way to import them back into the app.

So I had to explain to them how to use their app, and asked for at least JSON schemas to validate the generated files, since I could figure out the encryption on my own. After all, this should be in their best interest, so that people don't put annoying garbage into the app and possibly trigger exceptions. The answer was:

> > We will not provide JSON Schema to the public.

At least, to their credit, I haven't received a C&D letter yet, and I haven't noticed any black, unmarked cars following me on my way to the swimming pool so far. 

> PRs welcome.

I guess it depends on whether you're up for some collaborative development, or whether you insist on a perfect PR or nothing?

My problem at the moment is that the checklist format of ForeFlight is quite primitive. You can get an idea of what it might look like just by opening the app. They don't support much metadata about the checklist other than the name and description, and they only have 3 predefined subgroups (Normal, Abnormal, Emergency). Most of the items like notes and what not are not supported either.

So I'm having a bit of trouble mapping what I see in the file to your concepts, but that's only half the battle. Now, to regenerate the file, I would obviously have to weed out the unsupported stuff because it can't even be represented.

Now, one could argue that achieving a lossless roundtrip (load the ForeFLight checklist and export it as it was if there were no user modifications) is all we are aiming for. Modifications that cannot be represented will be partially changed silently (if possible) or dropped. Some things can be extended, like adding a description field to the metadata.  But I'm not sure where you stand on that.

Finally, I've never done frontend work, so all this stuff feels like torture, where things just don't work as expected from a backend engineer's perspective, and there are thousands of mostly outdated posts on the web about workarounds that are no longer relevant or were just plain wrong even at the time they were posted.

So if you don't want to help with that, I'd rather implement the ForeFlight models 1:1 (avoiding the mapping issues) in my Django loogbook app (https://github.com/zyv/pilot_log) and you'll be most welcome to steal the code / ideas from there. Python is mostly a good thing for mental health these days.

> Wild guess: if they let anyone write their checklist format, they have to make the app resilient to all sorts of badly-formatted files, as well as provide support for using checklists imported this way...

This sounds so dumb that you may actually have hit the nail on the head. Humanity is good at walking the fractal path of disappointment. Sigh.

**Comment by rdamazio** [comment]
> I guess it depends on whether you're up for some collaborative development, or whether you insist on a perfect PR or nothing?

Yes, I'm open to collaboration.

> They don't support much metadata about the checklist other than the name and description, and they only have 3 predefined subgroups (Normal, Abnormal, Emergency). Most of the items like notes and what not are not supported either.

That's true for most formats - the Dynon, GRT and AFS formats are basically just a text file, and I made up a mapping from the Garmin metadata to that, like surrounding titles with `*` :) what I saw from playing with FF is that they actually support more than Garmin in other respects, like how they group their checklists (they have a checklist "type" if I remember correctly?).

> At least, to their credit, I haven't received a C&D letter yet, and I haven't noticed any black, unmarked cars following me on my way to the swimming pool so far.

I'll refrain from commenting on any legal aspects of this in writing, for obvious reasons :) I'll defer to your judgment what to do about this.
(on a less serious note, beware of the small unmarked cars though - if it's a big van, they probably intend to take you alive :D :D )

> Now, one could argue that achieving a lossless roundtrip (load the ForeFLight checklist and export it as it was if there were no user modifications) is all we are aiming for. Modifications that cannot be represented will be partially changed silently (if possible) or dropped. 

That's what I've aimed for with other formats, and in fact the unit tests verify exactly that: https://github.com/rdamazio/efis-editor/blob/main/src/model/formats/grt-format.spec.ts#L18

> Some things can be extended, like adding a description field to the metadata. But I'm not sure where you stand on that.

If you mean adding metadata to the JSON file that Foreflight itself would not parse, I'm not opposed as long as it doesn't break FF importing.

> I've never done frontend work, so all this stuff feels like torture

I'm also a backend engineer :) (well, engineering manager nowadays) So I totally sympathize. A great fraction of my time creating this app was spent on Stackoverflow. I've tried to nerdsnipe frontend engineer friends to help, but was not successful. That said, when you remove CSS and such from the equation, Typescript is actually a very nice language IMHO - and for adding a file format we shouldn't have to do too much in terms of UI.

So I may not have all the answers, but I'm happy to help, either doing some of the work or helping you find answers.

**Comment by zyv** [comment]
> Yes, I'm open to collaboration.

Fantastic! What I will do then is achieve a roundtrip and open a pull request with TODOs in the code and general comments in the PR body. I think it will be much easier and more comfortable to discuss specific things if you can see the code. Then maybe you can do things you think should be done directly in the PR, when it's faster than explaining or telling me what you want me to do for bigger or controversial things.

What I'd like to ask first though is, could you please set up a linter and formatter to your liking beforehand? Or if you don't care enough, I can open a PR. Not sure about the latest fad in the frontend world, but this looks pretty standard:

https://github.com/angular-eslint/angular-eslint

If there is one thing that Go has got 120% right, it would be taking style out of the equation, if you ask me ;-) I'll go crazy trying to watch for quotes and semicolons for anything major.

> What I saw from playing with FF is that they actually support more than Garmin in other respects, like how they group their checklists (they have a checklist "type" if I remember correctly?).

I have no idea about Garmin, but I think I've finally figured out the ForeFlight structure and how it relates to your internal representation. Basically, you can think of it as your `ChecklistGroups` and `Checklists`, where existing `Checklists` must belong to at least one and at most one `ChecklistGroup`. However, each `ChecklistGroup` has a category (normal, abnormal, emergency) in their view. This corresponds nicely to the usual chapters in QRH books. Confusingly, they call their categories "groups" and the groups "subgroups".

So my idea is to introduce a new property in your internal representation (category) on `ChecklistGroup`, which will be ignored for formats that don't support it, but will allow me to flatten the ForeFlight structure one level to fit into your representation. I think this can be implemented in a practical and usable way.

Also, your `ChecklistItems` can have notes, and my idea is to translate these into two items in your representation, and then collapse them again when exporting. Which is suboptimal, but I'm not sure if you'll like extending `ChecklistItem` and if it's a great idea presentation-wise and modeling-wise.

> I'll refrain from commenting on any legal aspects of this in writing, for obvious reasons :) I'll defer to your judgment what to do about this.

According to my understanding of local laws (Germany), my work is protected, especially since it's clean-room reverse engineering, i.e. I deny having decompiled or disassembled the application, only having observed its activities and artifacts from the outside. But indeed, let's leave it at that :)

> (on a less serious note, beware of the small unmarked cars though - if it's a big van, they probably intend to take you alive :D :D )

Well, I'd actually be less worried about the van, given the recent history of freak accidental deaths of engineers involved in investigating Boeing problems, and ForeFlight is now owned by Boeing, so... <g>

> If you mean adding metadata to the JSON file that Foreflight itself would not parse, I'm not opposed as long as it doesn't break FF importing.

No, I meant modifying your models, like `ChecklistGroup` and `ChecklistFileMetadata`.

> I'm also a backend engineer :) (well, engineering manager nowadays) So I totally sympathize. 

Well, imagine what it feels like to a manager of (not just) engineering managers :) It's as you say, and I firmly believe that newer generations of front-end engineers should be eternally grateful to Microsoft's TypeScript and Google's Angular for saving them countless mental health problems, and layout and styling (including modern CSS) really isn't all that bad. Granted, I never bothered to understand flexboxes, but I vividly remember the days of IE 3 (with an obligatory NCSA Mosaic credit in the About box) and NN 4.75, `div` vs. `layer`, differences in box models, and so on...

My problem is more like for this project I'd like to have something like Pydantic for internal data modeling, runtime manipulation, serialization, deserialization, etc., and when it grows a bit so that it's worth using a declarative language, then I'd please like to have some more elaborate schema language. I'm sorry, but TypeScript interfaces and protocol buffers are just not much fun to work with for this application. I don't know if it's there, but you're not using it (I remember at least hearing about zod / valibot), or it's just not a thing in the front end.

Other than that, it's more like the frustration of spending hours on StackOverflow plowing through dozens of solutions for different combinations of Angular, Material, build stuff, etc. trying to figure out how the hell can I get the danger color from the Angular Material theme in the SCSS file so I can use those styles in the components, and giving up after realizing that you just went ahead and defined your CSS classes.

But that's part of entering a new territory where you don't know the local tricks and customs. You only grow by leaving your comfort zone... So thanks for a nice learning opportunity!

**Comment by zyv** [comment]
P.S. Another head-banging moment - `this` in JavaScript / TypeScript is such an unnecessary minefield... Try debugging `TypeError: undefined is not an object (evaluating 'this.classMethod')` thrown when mapping a static method to a collection from within another method. Note to self: always use class name as qualifier.

**Comment by rdamazio** [comment]
> > Yes, I'm open to collaboration.
> 
> Fantastic! What I will do then is achieve a roundtrip and open a pull request with TODOs in the code and general comments in the PR body. I think it will be much easier and more comfortable to discuss specific things if you can see the code. Then maybe you can do things you think should be done directly in the PR, when it's faster than explaining or telling me what you want me to do for bigger or controversial things.

Sounds good.

Btw, do read the "Contributing" section of the README - technically, my employer (Google) owns this project, so they require a CLA for contributions.

> What I'd like to ask first though is, could you please set up a linter and formatter to your liking beforehand? Or if you don't care enough, I can open a PR. Not sure about the latest fad in the frontend world, but this looks pretty standard:
> 
> https://github.com/angular-eslint/angular-eslint

Sure. I'll try to do that this weekend.

> > What I saw from playing with FF is that they actually support more than Garmin in other respects, like how they group their checklists (they have a checklist "type" if I remember correctly?).
> 
> I have no idea about Garmin, but I think I've finally figured out the ForeFlight structure and how it relates to your internal representation. Basically, you can think of it as your `ChecklistGroups` and `Checklists`, where existing `Checklists` must belong to at least one and at most one `ChecklistGroup`. However, each `ChecklistGroup` has a category (normal, abnormal, emergency) in their view. This corresponds nicely to the usual chapters in QRH books. Confusingly, they call their categories "groups" and the groups "subgroups".
>
> So my idea is to introduce a new property in your internal representation (category) on `ChecklistGroup`, which will be ignored for formats that don't support it, but will allow me to flatten the ForeFlight structure one level to fit into your representation. I think this can be implemented in a practical and usable way.

Yeah, we don't have to match their nomenclature, but adding a category enum to the groups should work.

> Also, your `ChecklistItems` can have notes, and my idea is to translate these into two items in your representation, and then collapse them again when exporting. Which is suboptimal, but I'm not sure if you'll like extending `ChecklistItem` and if it's a great idea presentation-wise and modeling-wise.

Yeah, I guess that does match the intent - if I wanted to add a Foreflight-like note to my G3X's checklist, I'd use a separate note entry right after (probably indented by 1).

> > If you mean adding metadata to the JSON file that Foreflight itself would not parse, I'm not opposed as long as it doesn't break FF importing.
> 
> No, I meant modifying your models, like `ChecklistGroup` and `ChecklistFileMetadata`.

Yeah, feel free to propose changes to those.

> > I'm also a backend engineer :) (well, engineering manager nowadays) So I totally sympathize.
> 
> Well, imagine what it feels like to a manager of (not just) engineering managers :)

Yes, I know exactly what that feels like, I have managers of managers reporting to me :)

> It's as you say, and I firmly believe that newer generations of front-end engineers should be eternally grateful to Microsoft's TypeScript

>  and Google's Angular 

You're welcome :) (I never worked *on* Angular, but they use the infrastructure my teams build)

> for saving them countless mental health problems, and layout and styling (including modern CSS) really isn't all that bad. Granted, I never bothered to understand flexboxes, but I vividly remember the days of IE 3 (with an obligatory NCSA Mosaic credit in the About box) and NN 4.75, `div` vs. `layer`, differences in box models, and so on...

Now you're bringing back a lot of bad memories 😆 

> My problem is more like for this project I'd like to have something like Pydantic for internal data modeling, runtime manipulation, serialization, deserialization, etc., and when it grows a bit so that it's worth using a declarative language, then I'd please like to have some more elaborate schema language. I'm sorry, but TypeScript interfaces and protocol buffers are just not much fun to work with for this application. I don't know if it's there, but you're not using it (I remember at least hearing about zod / valibot), or it's just not a thing in the front end.

The declarative thing for data processing does exist in Typescript - it's React (and ngrx is the Angular flavor of that). It adds way too much complexity for my taste though, especially on a small project like this.

> Other than that, it's more like the frustration of spending hours on StackOverflow plowing through dozens of solutions for different combinations of Angular, Material, build stuff, etc. trying to figure out how the hell can I get the danger color from the Angular Material theme in the SCSS file so I can use those styles in the components, and giving up after realizing that you just went ahead and defined your CSS classes.

I'll admit: I don't understand how Angular color mixins really work 😄 so I'm sure there's a more "correct" way to do it than overriding colors like I did, but I also gave up trying to figure it out and hope that some day, someone who really understands it will send a PR (and if it not, well, it's working well enough).

> But that's part of entering a new territory where you don't know the local tricks and customs. You only grow by leaving your comfort zone... So thanks for a nice learning opportunity!

No problem 😺

**Comment by rdamazio** [comment]
Added ESLint as you requested.

**Comment by zyv** [comment]
> Added ESLint as you requested.

Awesome, thank you very much! I'm almost done reading and writing. I wanted to check next if ForeFlight would load the files I'm writing at all (still not sure what `objectId` is all about), and then try to get a roundtrip to work. So I was about to ask... What about the formatter though, does `eslint` take care of that now, or is `prettier` still needed?

**Comment by rdamazio** [comment]
Awesome!

> So I was about to ask... What about the formatter though, does eslint take care of that now, or is prettier still needed?

I've mostly just been asking VSCode to format the files for me: https://code.visualstudio.com/docs/languages/typescript#_formatting

**Comment by zyv** [comment]
> Yes, I know exactly what that feels like, I have managers of managers reporting to me :)

Well, let's see what two managers of managers can manage in terms of getting their own hands dirty :) I've just opened #51 - hacking the format was easy, but preparing a proper contribution to my standards took time.

> Btw, do read the "Contributing" section of the README - technically, my employer (Google) owns this project, so they require a CLA for contributions.

No problem, I've contributed to several Google projects and have no problem with the CLA.

> You're welcome :) (I never worked on Angular, but they use the infrastructure my teams build)

Kudos for that! Angular people just get so many things right 👍

> Now you're bringing back a lot of bad memories 😆

I assert that the grass runways were greener back then! 🤣 

> I'll admit: I don't understand how Angular color mixins really work 😄 

Well, now there are two of us! 😉 Hopefully one day someone will come to the rescue, but for me there are other battles to fight.

> The declarative thing for data processing does exist in Typescript - it's React (and ngrx is the Angular flavor of that). It adds way too much complexity for my taste though, especially on a small project like this.

I guess you meant **Redux**, right - React is the evil twin of Angular 😝 But that is not exactly what I meant. Maybe you should check out the new version of Pydantic if you haven't had the chance yet:

https://docs.pydantic.dev/latest/

This is basically what I want to see in terms of models coming out of `genproto`. Strongly typed, with runtime type checking and constraints, serialization and deserialization included.

On top of that, a powerful schema format instead of Protobuf to actually be able to describe all this would be nice.

At my shop we used OpenAPI everywhere and had to implement something like Pydantic for TypeScript and the integration with Angular ourselves.
