### ISSUE TITLE
Support reordering checklist groups

### ISSUE THREAD

**Issue by kpaonaut** [rdamazio/efis-editor#73]
Hi, how much complexity would it involve to support reordering checklist groups (right now only checklist items can be dragged and reordered)? Thanks!

**Comment by rdamazio** [comment]
The actual reordering is easy, and I can add keyboard shortcuts that do it today (like the existing shortcut to reorder items).

The drag-and-drop UI is a little more involved, at least for me :) if you have Angular/Material experience and/or want to give that a try, I'm happy to try to help.

**Comment by rdamazio** [comment]
Keyboard shortcuts added - please try that out. (will be available about 3 minutes after I send this)

Minor caveat that there's no way to reorder a group that has no checklists in it, you need to have a checklist selected to reorder its group.
Also, I've only tested on a Mac, let me know if there's any weird keyboard shortcut behavior on another platform.

**Comment by kpaonaut** [comment]
Appreciate the prompt response! I have zero front end knowledge but maybe I'll take a closer look into this later!

So, I tried the shortcut on my Mac:
* Select a checklist group.
* Press shift+option+up

Nothing happens. Did I do something wrong here?

**Comment by rdamazio** [comment]
> Select a checklist group.

Did you try selecting a checklist within the group then hitting the shortcut?
(there's currently no way to "select" a group, which is also why you can't move a group without a checklist in it)

**Comment by kpaonaut** [comment]
> > Select a checklist group.
> 
> Did you try selecting a checklist within the group then hitting the shortcut? (there's currently no way to "select" a group, which is also why you can't move a group without a checklist in it)

Looked at your code more carefully and it works now. Appreciate it!

**Comment by rdamazio** [comment]
FYI I just added drag and drop for checklists on the left-side tree (not yet for groups), please try it out and file bugs if you see any issues.
